#!/bin/bash
# Update .env on Hostinger server

TARGET="/home/u933773389/domains/gombesshub.com/public_html"

# Create/update .env file
cat > "$TARGET/.env" << 'EOF'
APP_NAME=Gombesshub
APP_ENV=production
APP_KEY=base64:1cJVMJW5CujfAQxy6FgVwRWvtrxAfSlOX1lHpBqbHZo=
APP_DEBUG=false
APP_URL=https://gombesshub.com
APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US
APP_MAINTENANCE_DRIVER=file
PHP_CLI_SERVER_WORKERS=4
BCRYPT_ROUNDS=12
LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=u933773389_gombe_ss_hub
DB_USERNAME=u933773389_deployed_ombe
DB_PASSWORD=Wasswa@25
SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null
BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
CACHE_STORE=file
MEMCACHED_HOST=127.0.0.1
REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
MAIL_MAILER=smtp
MAIL_HOST=smtp.hostinger.com
MAIL_PORT=465
MAIL_USERNAME=YOUR_REAL_EMAIL@YOURDOMAIN.com
MAIL_PASSWORD=YOUR_REAL_EMAIL_PASSWORD
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS=YOUR_REAL_EMAIL@YOURDOMAIN.com
MAIL_FROM_NAME=Gombesshub
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false
VITE_APP_NAME=Gombesshub
EOF

# Set permissions
chmod 644 "$TARGET/.env"

# Clear config cache
cd "$TARGET"
php artisan config:cache

echo ".env file updated successfully!"
